Added bsf clean Command to Remove Autogenerated Files
buildsafedev/bsf pull request #121
Opened 2024-10-12 16:02 UTC by RohanMishra315

#120 

Description:
This PR introduces a new bsf clean command that simplifies the cleanup of autogenerated files and directories during development. This feature is especially useful when testing new features or iterating locally, where manual deletion of these files is often needed.

Key Features:
 1. New bsf clean Command:

The bsf clean command deletes the following autogenerated files and directories:
bsf/
bsf-result/
bsf.hcl
bsf.lock

2. Reused Cleanup Logic:

Reuses the cleanup logic from cmd/init, ensuring consistency and reducing code duplication.

2024-10-12 16:44 UTC, rakshitgondwal commented on cmd/clean/clean.go
> +	rootCmd.AddCommand(cleanCmd)
This logic should go over here:
https://github.com/buildsafedev/bsf/blob/a2c73d1a07c03290df94270b30c687bac5491b41/cmd/cmd.go#L70

2024-10-12 16:46 UTC, rakshitgondwal commented on cmd/clean/clean.go
> +	Short: "Clean autogenerated BSF files and directories",
```suggestion
	Short: "cleans the autogenerated bsf files and directories",
```

2024-10-12 16:47 UTC, rakshitgondwal commented on cmd/clean/clean.go
> +	configs := []string{"bsf", "bsf-result", "bsf.hcl", "bsf.lock"}
Will this give an error if `bsf-result` is not already present? Please check once

2024-10-12 16:48 UTC, rakshitgondwal commented on cmd/clean/clean.go
> +func cleanUp() error {
Please reuse the logic which is already present under `cmd/init`

2024-10-12 16:49 UTC, rakshitgondwal commented on cmd/clean/clean.go
> +		}
We don't really need this as the command will only be initialized if `BSF_DEBUG_MODE` is enabled.

2024-10-12 16:55 UTC, rakshitgondwal commented on cmd/clean/clean.go
> +		}
```suggestion
		if err := cleanUp(); err != nil {
			fmt.Println(styles.ErrorStyle.Render("error during cleanup:", err.Error()))
			os.Exit(1)
		}
		fmt.Println(styles.SucessStyle.Render("autogenerated bsf files/dirs cleaned successfully"))
```

2024-10-12 16:56 UTC, rakshitgondwal requested changes
Thanks for the PR! Can you please sign your commits?

2024-10-12 17:56 UTC, RohanMishra315 commented
> Thanks for the PR! Can you please sign your commits?

Done , pls check it and anything to add let me know

2024-10-13 10:59 UTC, rakshitgondwal reviewed
> Done , pls check it and anything to add let me know

Thanks for making the changes @RohanMishra315. The commits are still not signed and some of the comments are still unaddressed, please fix those as well. Additionally, can you add yourself in the `./CONTRIBUTORS.md` file as well?

2024-10-13 11:00 UTC, rakshitgondwal commented on cmd/clean/clean.go
> +	configs := []string{"bsf", "bsf-result", "bsf.hcl", "bsf.lock"}
Did you check this? Was it giving an error?

2024-10-16 18:36 UTC, rakshitgondwal commented
Hi @RohanMishra315, let me know if you need any help

2024-10-25 14:19 UTC, rakshitgondwal commented
Hi @RohanMishra315, checking up on this again

2024-11-19 16:25 UTC, rakshitgondwal commented
Fixed in https://github.com/buildsafedev/bsf/pull/128

2024-11-19 16:25 UTC, closed without merging